version: 3
pullapprove_conditions:
  - "'WIP' not in title"
  - "base.ref == 'master'"
  - "'hotfix' not in labels"
  - "'*travis*' in statuses.succeeded"

notifications:
  - when: pull_request.opened
    # only need to send this to external-contributors
    if: "author_association in ['FIRST_TIMER', 'FIRST_TIME_CONTRIBUTOR', 'CONTRIBUTOR']"
    comment: >
      Hey @{{ author }}, please make sure your tests pass and you have looked everything over. Then we will review.

      Thanks for the PR!
  - when: pullapprove.approved
    comment: "The review is completed. @{{ author }}, please merge this in when ready."

groups:
  code:
    reviewers:
      users:
        - TommyLike
        - zhongjun2
    reviews:
      required: 2  # number of approvals required from this group
      request: 2  # number of review requests sent at a time
      request_order: random  # "random" or "given"
    labels:
      approved: "Code review approved"
      pending: "Code review pending"
      rejected: "Code review rejected"
